services:
  - type: web
    name: sta-reg-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HF_TOKEN
        sync: false
    pythonVersion: 3.10
